### ISSUE TITLE
Install.sh fails when trying to build and install

### ISSUE THREAD

**Issue by wildcat26** [convict-git/cp_parser_cli#1]
1. `build.sh` runs successfully after the following change at line 29, `if node node_modules/pkg --targets node10-linux-x64 index.js -o ./bin/cp-parse;`. Don't know if this is advisable.

2. Binaries are not generated in `./bin/`. However, three scripts have been copied to `/usr/bin`.

**Comment by wildcat26** [comment]
![image](https://user-images.githubusercontent.com/37037236/107506884-c488e500-6bc4-11eb-916e-c1367b6704c1.png)

**Comment by wildcat26** [comment]
![image](https://user-images.githubusercontent.com/37037236/107506924-d2d70100-6bc4-11eb-84a9-8c5e22782cd0.png)

**Comment by convict-git** [comment]
The bug was in `create-package.sh`
```bash
cp -v ./bin/cp-parse ./package/bin &&
```
This creates rather an executable named bin instead of copying into bin since bin wasn't created at all before. Will fix it in the next push.
